<?php

return array(
	array(
		'name'   => 'JNews_Video_Categorylist',
		'type'   => 'carousel',
		'image'  => '',
		'widget' => true,
		'view'   => '/class/module/element/class.jnews-category-module-view.php',
		'option' => '/class/module/element/class.jnews-category-module-option.php',
	),
	array(
		'name'   => 'JNews_Video_Videoheader',
		'type'   => 'header',
		'image'  => '',
		'widget' => true,
		'view'   => '/class/module/element/class.jnews-video-header-view.php',
		'option' => '/class/module/element/class.jnews-video-header-option.php',
	),
	array(
		'name'   => 'JNews_Video_Block1',
		'alias'  => 'video_1',
		'type'   => 'block',
		'image'  => JNEWS_VIDEO_URL . '/assets/img/admin/content-video-1.png',
		'widget' => true,
		'view'   => '/class/module/block/class.jnews-video-block-1-view.php',
		'option' => '/class/module/block/class.jnews-video-block-1-option.php',
	),
	array(
		'name'   => 'JNews_Video_Block2',
		'alias'  => 'video_2',
		'type'   => 'block',
		'image'  => JNEWS_VIDEO_URL . '/assets/img/admin/content-video-2.png',
		'widget' => true,
		'view'   => '/class/module/block/class.jnews-video-block-2-view.php',
		'option' => '/class/module/block/class.jnews-video-block-2-option.php',
	),
	array(
		'name'   => 'JNews_Video_Block3',
		'alias'  => 'video_3',
		'type'   => 'block',
		'image'  => JNEWS_VIDEO_URL . '/assets/img/admin/content-video-3.png',
		'widget' => true,
		'view'   => '/class/module/block/class.jnews-video-block-3-view.php',
		'option' => '/class/module/block/class.jnews-video-block-3-option.php',
	),
	array(
		'name'   => 'JNews_Video_Block4',
		'alias'  => 'video_4',
		'type'   => 'block',
		'image'  => JNEWS_VIDEO_URL . '/assets/img/admin/content-video-4.png',
		'widget' => true,
		'view'   => '/class/module/block/class.jnews-video-block-4-view.php',
		'option' => '/class/module/block/class.jnews-video-block-4-option.php',
	),
	array(
		'name'   => 'JNews_Video_Carousel1',
		'type'   => 'carousel',
		'image'  => '',
		'widget' => true,
		'view'   => '/class/module/carousel/class.jnews-video-carousel-1-view.php',
		'option' => '/class/module/carousel/class.jnews-video-carousel-1-option.php',
	),
	array(
		'name'   => 'JNews_Video_Carousel2',
		'type'   => 'carousel',
		'image'  => '',
		'widget' => true,
		'view'   => '/class/module/carousel/class.jnews-video-carousel-2-view.php',
		'option' => '/class/module/carousel/class.jnews-video-carousel-2-option.php',
	),
	array(
		'name'   => 'JNews_Video_Carousel3',
		'type'   => 'carousel',
		'image'  => '',
		'widget' => true,
		'view'   => '/class/module/carousel/class.jnews-video-carousel-3-view.php',
		'option' => '/class/module/carousel/class.jnews-video-carousel-3-option.php',
	),
	array(
		'name'   => 'JNews_Video_Carousel4',
		'type'   => 'carousel',
		'image'  => '',
		'widget' => true,
		'view'   => '/class/module/carousel/class.jnews-video-carousel-4-view.php',
		'option' => '/class/module/carousel/class.jnews-video-carousel-4-option.php',
	),
	array(
		'name'   => 'JNews_Video_Carouselplaylist',
		'type'   => 'carousel',
		'image'  => '',
		'widget' => true,
		'view'   => '/class/module/element/class.jnews-playlist-carousel-view.php',
		'option' => '/class/module/element/class.jnews-playlist-carousel-option.php',
	),
	array(
		'name'   => 'JNews_Video_Blockplaylist',
		'type'   => 'block',
		'image'  => '',
		'widget' => true,
		'view'   => '/class/module/element/class.jnews-playlist-block-view.php',
		'option' => '/class/module/element/class.jnews-playlist-block-option.php',
	),
);
